### PR TITLE
further memory optimization and decoupled updating the mesh from drawing

### PR DESCRIPTION
**Pull request by tbd-vam**
changed as described in
https://github.com/Yoooi0/vam-debug-utils/pull/1#issuecomment-1792234213

and exposed updating and drawing the mesh as separate methods to run them in Update() and FixedUpdate() or at different fps in general.

### CODE REVIEW

**Comment by Yoooi0** [comment]
> and exposed updating and drawing the mesh as separate methods to run them in Update() and FixedUpdate() or at different fps in general.

Why would you want that?

**Comment by Yoooi0** [comment]
> GetIndices returns a copy, Array.Resize creates another array and copies the content, the loop overwrites everything in the array anyway.

GetIndices returns a copy but it is also prefilled with previous indices, which could be used to optimize the for loop. 
But you are right it should not be called on each call.

edit: Also Array.Resize creates only if the size is different. It does not do anything if its the same.

**Comment by tbd-vam** [comment]
If the indices array's size doesn't change there's no need to update the mesh's indices at all. Thus, Array.Resize always creates a new array when it's needed.

> Why would you want that?

Because I'm drawing so many vertices that it has an impact on fps if it's refreshed every frame. Updating it at about 23 fps is enough.

**Comment by Yoooi0** [comment]
Reordered some stuff, should work the same

**Pull request merged**
