### PR TITLE
added buffers

### PR DESCRIPTION
**Pull request by tbd-vam**
There was a rapid growth in heap size when drawing lots of skeletons in TBD.BodyNet. Most of it was due to new arrays being created every frame.
Also, I wanted to be able to draw on Update() but only change what is drawn on every N'th FixedUpdate(). This was pretty much free with this change.

### CODE REVIEW

**Comment by Yoooi0** [comment]
You are still creating a lot of arrays each time the vertex buffer changes, the only array that needs to match the vertex count is the index array, others can have reserve capacity. Pushed a fix to reuse the arrays, let me know how it works.

**Comment by tbd-vam** [comment]
Mesh.vertices specifies that it returns a copy, that's why I didn't think reusing it mattered. The other arrays were recreated only when the vertex count changed, which is very rarely in our plugins.
Your implementation is better, though. I just put the code to draw the unchanged mesh back in.

**Comment by Yoooi0** [comment]
Yea I missed that its a copy, simplified further. Now only indices are copied, seems like vam unity version does not have `SetIndices` with a list as parameter.

**Comment by tbd-vam** [comment]
I did some testing and the rate at which the heap grows is a bit quicker with your implementation.
When drawing 16456 vertices it took your implementation 26 draws to fill up 1GB vs 30 draws with mine.

This might be because you're reassigning normals and uvs on every cycle.
Each of the mesh's array properties boil down to an external Unity call
```
[MethodImpl(MethodImplOptions.InternalCall)]
[FreeFunction(Name = "SetMeshComponentFromArrayFromScript", HasExplicitThis = true)]
private extern void SetArrayForChannelImpl(InternalShaderChannel channel, InternalVertexChannelType format, int dim, Array values, int arraySize);
```

Since the Mesh's vertices property's documentation specifies that it's assigning and returning copies, I assume the same is true for the other properties.

**Comment by tbd-vam** [comment]
Never mind, I didn't realize you pushed another commit getting rid of normals and uvs altogether.
Now, there's only one thing left.
```
var indices = _mesh.GetIndices(0);
Array.Resize(ref indices, _vertices.Count);
for (var i = 0; i < _vertices.Count; i++)
    indices[i] = i;

_mesh.SetIndices(indices, MeshTopology.Lines, 0, calculateBounds: true);
```

GetIndices returns a copy, Array.Resize creates another array and copies the content, the loop overwrites everything in the array anyway.

The result is exactly the same as
```
if (numberOfVerticesHasChanged)
{
    var indices = new int[_vertices.Count];
    for (var i = 0; i < _vertices.Count; i++)
        indices[i] = i;
    _mesh.SetIndices(indices, MeshTopology.Lines, 0, calculateBounds: true);
}
else
    _mesh.RecalculateBounds();
```

**Pull request closed without merging**
